
export const useEmojiData = () => {
    const emojiCategories = {
        smileys: [
          { emoji: '😀', description: 'Grinning Face' }, 
          { emoji: '😁', description: 'Beaming Face with Smiling Eyes' }, 
          { emoji: '😆', description: 'Grinning Squinting Face' }, 
          { emoji: '🥹', description: 'Smiling Face with Tears' }, 
          { emoji: '😅', description: 'Grinning Face with Sweat' }, 
          { emoji: '😂', description: 'Laughing Face with Tears of Joy' }, 
          { emoji: '🤣', description: 'Rolling on the Floor Laughing Face' }, 
          { emoji: '🥲', description: 'Smiling Face with Tear' }, 
          { emoji: '😊', description: 'Smiling Face with Smiling Eyes'} , 
          { emoji: '😇', description: 'Smiling Face with Halo' }, 
          { emoji: '🙂', description: 'Slightly Smiling Face' }, 
          { emoji: '🙃', description: 'Upside-Down Smiling Face' }, 
          { emoji: '😉', description: 'Winking Face' }, 
          { emoji: '😌', description: 'Relieved Face' },
          { emoji: '😍', description: 'Face with Heart-Eyes' }, 
          { emoji: '🥰', description: 'Smiling Face with Hearts' }, 
          { emoji: '😘', description: 'Face Blowing a Kiss' }, 
          { emoji: '😋', description: 'Face Savoring Food' }, 
          { emoji: '😛', description: 'Face with Tongue Sticking Out' }, 
          { emoji: '😝', description: 'Squinting Face with Tongue Sticking Out' }, 
          { emoji: '😜', description: 'Winking Face with Tongue Sticking Out' }, 
          { emoji: '🤪', description: 'Zany Face with Tongue Sticking Out' }, 
          { emoji: '🤨', description: 'Face with Raised Eyebrow' }, 
          { emoji: '🧐', description: 'Face with Monocle' }, 
          { emoji: '🤓', description: 'Nerd Face' }, 
          { emoji: '😎', description: 'Smiling Face with Sunglasses' },
          { emoji: '🥸', description: 'Disguised Face' }, 
          { emoji: '🤩', description: 'Star-Struck Face' }, 
          { emoji: '🥳', description: 'Partying Face' }, 
          { emoji: '😏', description: 'Smirking Face' }, 
          { emoji: '😒', description: 'Unamused Face' }, 
          { emoji: '😞', description: 'Disappointed Face' }, 
          { emoji: '😔', description: 'Pensive Face' }, 
          { emoji: '😟', description: 'Worried Face' }, 
          { emoji: '😕', description: 'Confused Face' }, 
          { emoji: '😣', description: 'Persevering Face' }, 
          { emoji: '😖', description: 'Confused Face' }, 
          { emoji: '😫', description: 'Frustrated Face' }, 
          { emoji: '🥺', description: 'Pleading Face' }, 
          { emoji: '😢', description: 'Crying Face with One Tear' }, 
          { emoji: '😭', description: 'Face Crying Heavily' }, 
          { emoji: '😤', description: 'Face with Steam from Nose' }, 
          { emoji: '😠', description: 'Angry Face' }, 
          { emoji: '😡', description: 'Very Angry Face' }, 
          { emoji: '🤬', description: 'Swearing Face' }, 
          { emoji: '🤯', description: 'Exploding Head' }, 
          { emoji: '😳', description: 'Shocked Face' }, 
          { emoji: '🥵', description: 'Hot Face' }, 
          { emoji: '🥶', description: 'Cold Face' }, 
          { emoji: '😱', description: 'Face Screaming in Fear' }, 
          { emoji: '😨', description: 'Fearful Face' }, 
          { emoji: '😰', description: 'Anxious Face with Sweat' }, 
          { emoji: '🤗', description: 'Hugging face' }, 
          { emoji: '🤔', description: 'Thinking Face' }, 
          { emoji: '🫣', description: 'Face with Hands Over Mouth and Eyes' }, 
          { emoji: '🤭', description: 'Smiling Face with Hand Over Mouth' }, 
          { emoji: '🫢', description: 'Face with Hand Over Mouth' }, 
          { emoji: '🤫', description: 'Shushing Face' }, 
          { emoji: '🫠', description: 'Melting Face' }, 
          { emoji: '😶', description: 'Face Without Mouth' }, 
          { emoji: '😐', description: 'Neutral Face' }, 
          { emoji: '😑', description: 'Expressionless Face' }, 
          { emoji: '😬', description: 'Grimacing Face' }, 
          { emoji: '🙄', description: 'Face with Rolling Eyes' }, 
          { emoji: '😯', description: 'Hushed Face' }, 
          { emoji: '😦', description: 'Face with Open Mouth' }, 
          { emoji: '🥱', description: 'Yawning Face' }, 
          { emoji: '😴', description: 'Sleeping Face' }, 
          { emoji: '🤤', description: 'Drooling Face' }, 
          { emoji: '😮‍💨', description: 'Exhaling Face' }, 
          { emoji: '🥴', description: 'Woozy Face' }, 
          { emoji: '🤢', description: 'Nauseated Face' }, 
          { emoji: '🤮', description: 'Vomiting Face' }, 
          { emoji: '🤧', description: 'Blowing Nose Face' }, 
          { emoji: '😷', description: 'Face with Medical Mask' }, 
          { emoji: '🤒', description: 'Face with Thermometer' }, 
          { emoji: '🤕', description: 'Face with Head Bandage' }, 
          { emoji: '🤑', description: 'Money-Mouth Face' }, 
          { emoji: '🤠', description: 'Face Wearing Cowboy Hat' }, 
          { emoji: '😈', description: 'Purple Devil Grinning Face' }, 
          { emoji: '👿', description: 'Purple Devil Frowning Face' }, 
          { emoji: '👹', description: 'Ogre' }, 
          { emoji: '👺', description: 'Goblin' }, 
          { emoji: '🤡', description: 'Clown' }, 
          { emoji: '💩', description: 'Poop' }, 
          { emoji: '👻', description: 'Ghost' }, 
          { emoji: '💀', description: 'Skull' }, 
          { emoji: '👽', description: 'Alien' }, 
          { emoji: '🤖', description: 'Robot' }, 
          { emoji: '🎃', description: 'Face Carved into Pumpkin' } 
        ],
    
        animals: [
          { emoji: '🐶', description: 'Dog Face' }, 
          { emoji: '🐱', description: 'Cat Face' }, 
          { emoji: '🐭', description: 'Mouse Face' }, 
          { emoji: '🐹', description: 'Hamster Face' }, 
          { emoji: '🐰', description: 'Rabbit Face' }, 
          { emoji: '🦊', description: 'Fox Face' }, 
          { emoji: '🐻', description: 'Bear Face'}, 
          { emoji: '🐼', description: 'Panda Face'}, 
          { emoji: '🐻‍❄️', description: 'Polar Bear Face' }, 
          { emoji: '🐨', description: 'Koala Face' }, 
          { emoji: '🐯', description: 'Tiger Face' }, 
          { emoji: '🦁', description: 'Lion Face' }, 
          { emoji: '🐮', description: 'Cow Face' }, 
          { emoji: '🐷', description: 'Pig Face' }, 
          { emoji: '🐽', description: 'Pig Nose' }, 
          { emoji: '🐸', description: 'Frog Face' }, 
          { emoji: '🐵', description: 'Monkey Face' }, 
          { emoji: '🙈', description: 'See-No-Evil Monkey' }, 
          { emoji: '🙉', description: 'Hear-No-Evil Monkey' }, 
          { emoji: '🙊', description: 'Speak-No-Evil Monkey' }, 
          { emoji: '🐒', description: 'Monkey' }, 
          { emoji: '🐔', description: 'Chicken' }, 
          { emoji: '🐧', description: 'Penguin' }, 
          { emoji: '🐦', description: 'Bird' }, 
          { emoji: '🐤', description: 'Chick Face' }, 
          { emoji: '🐣', description: 'Hatching Chick' }, 
          { emoji: '🐥', description: 'Chick'}, 
          { emoji: '🦆', description: 'Duck' }, 
          { emoji: '🦅', description: 'Eagle' }, 
          { emoji: '🦉', description: 'Owl' }, 
          { emoji: '🦇', description: 'Bat' }, 
          { emoji: '🐺', description: 'Wolf' }, 
          { emoji: '🐗', description: 'Boar' }, 
          { emoji: '🐴', description: 'Horse' }, 
          { emoji: '🦄', description: 'Unicorn' }, 
          { emoji: '🐝', description: 'Bee' }, 
          { emoji: '🪱', description: 'Worm' }, 
          { emoji: '🐛', description: 'Bug' }, 
          { emoji: '🦋', description: 'Butterfly' }, 
          { emoji: '🐌', description: 'Snail' }, 
          { emoji: '🐞', description: 'Ladybug' }, 
          { emoji: '🐜', description: 'Ant' }, 
          { emoji: '🪰', description: 'Fly' }, 
          { emoji: '🪲', description: 'Beetle' }, 
          { emoji: '🪳', description: 'Cockroach' }, 
          { emoji: '🦟', description: 'Mosquito' }, 
          { emoji: '🦗', description: 'Cricket' }, 
          { emoji: '🕷', description: 'Spider' }, 
          { emoji: '🕸', description: 'Spider Web' }, 
          { emoji: '🦂', description: 'Scorpion' }, 
          { emoji: '🐢', description: 'Turtle' }, 
          { emoji: '🐍', description: 'Snake' }, 
          { emoji: '🦎', description: 'Lizard' }, 
          { emoji: '🦖', description: 'T-Rex' }, 
          { emoji: '🦕', description: 'Sauropod' }, 
          { emoji: '🐙', description: 'Octupus' }, 
          { emoji: '🦑', description: 'Squid' }, 
          { emoji: '🦐', description: 'Shrimp' }, 
          { emoji: '🦞', description: 'Lobster' }, 
          { emoji: '🦀', description: 'Crab' }, 
          { emoji: '🐡', description: 'Blowfish' }, 
          { emoji: '🐠', description: 'Tropical Fish' }, 
          { emoji: '🐟', description: 'Fish' }, 
          { emoji: '🐬', description: 'Dolphin' }, 
          { emoji: '🐳', description: 'Spouting Whale' }, 
          { emoji: '🐋', description: 'Whale' }, 
          { emoji: '🦈', description: 'Shark' }, 
          { emoji: '🐊', description: 'Crocodile' }, 
          { emoji: '🐅', description: 'Tiger' }, 
          { emoji: '🐆', description: 'Leopard' }, 
          { emoji: '🦓', description: 'Zebra' }, 
          { emoji: '🦍', description: 'Gorilla' }, 
          { emoji: '🦧', description: 'Orangutan' }, 
          { emoji: '🦣', description: 'Mammoth' }, 
          { emoji: '🐘', description: 'Elephant' }, 
          { emoji: '🦛', description: 'Hippopotamus' }, 
          { emoji: '🦏', description: 'Rhinoceros' }, 
          { emoji: '🐪', description: 'Camel' }, 
          { emoji: '🐫', description: 'Two-Hump Camel' }, 
          { emoji: '🦒', description: 'Giraffe' }, 
          { emoji: '🦘', description: 'Kangaroo' }, 
          { emoji: '🦬', description: 'Bison' }, 
          { emoji: '🐃', description: 'Water Buffalo' }, 
          { emoji: '🐂', description: 'Ox' }, 
          { emoji: '🐄', description: 'Cow' }, 
          { emoji: '🐎', description: 'Horse' }, 
          { emoji: '🐖', description: 'Pig' }, 
          { emoji: '🐏', description: 'Ram' }, 
          { emoji: '🐑', description: 'Ewe' }, 
          { emoji: '🦙', description: 'Llama' }, 
          { emoji: '🐐', description: 'Goat' }, 
          { emoji: '🦌', description: 'Deer' }, 
          { emoji: '🐕', description: 'Dog' }, 
          { emoji: '🐩', description: 'Poodle' }, 
          { emoji: '🦮', description: 'Guide Dog' }, 
          { emoji: '🐕‍🦺', description: 'Service Dog' }, 
          { emoji: '🐈', description: 'Cat' }, 
          { emoji: '🐓', description: 'Rooster' } 
        ],
    
        food: [
          { emoji: '🍏', description: 'Green Apple' }, 
          { emoji: '🍎', description: 'Red Apple' }, 
          { emoji: '🍐', description: 'Pear' }, 
          { emoji: '🍊', description: 'Tangerine' }, 
          { emoji: '🍋', description: 'Lemon' }, 
          { emoji: '🍌', description: 'Banana' }, 
          { emoji: '🍉', description: 'Watermelon' }, 
          { emoji: '🍇', description: 'Grapes' }, 
          { emoji: '🍓', description: 'Stawberry' }, 
          { emoji: '🫐', description: 'Blueberries' }, 
          { emoji: '🍈', description: 'Melon' }, 
          { emoji: '🍒', description: 'Cherries' }, 
          { emoji: '🍑', description: 'Peach' }, 
          { emoji: '🥭', description: 'Mango' }, 
          { emoji: '🍍', description: 'Pineapple' }, 
          { emoji: '🥥', description: 'Coconut' }, 
          { emoji: '🥝', description: 'Kiwi' }, 
          { emoji: '🍅', description: 'Tomato' }, 
          { emoji: '🫒', description: 'Olive' }, 
          { emoji: '🥑', description: 'Avocado' }, 
          { emoji: '🍆', description: 'Eggplant' }, 
          { emoji: '🥔', description: 'Potato' }, 
          { emoji: '🥕', description: 'Carrot' }, 
          { emoji: '🌽', description: 'Corn' }, 
          { emoji: '🌶', description: 'Hot Pepper' }, 
          { emoji: '🫑', description: 'Bell Pepper'}, 
          { emoji: '🥒', description: 'Cucumber' }, 
          { emoji: '🥬', description: 'Leafy Green' }, 
          { emoji: '🥦', description: 'Brocolli' }, 
          { emoji: '🧄', description: 'Garlic' }, 
          { emoji: '🧅', description: 'Onion' }, 
          { emoji: '🍄', description: 'Mushroom' }, 
          { emoji: '🥜', description: 'Peanuts' }, 
          { emoji: '🌰', description: 'Chestnut' }, 
          { emoji: '🍞', description: 'Bread' }, 
          { emoji: '🥐', description: 'Croissant' }, 
          { emoji: '🥖', description: 'Baguette Bread' }, 
          { emoji: '🥨', description: 'Pretzel' }, 
          { emoji: '🥯', description: 'Bagel' }, 
          { emoji: '🥞', description: 'Pancakes' }, 
          { emoji: '🧇', description: 'Waffle' }, 
          { emoji: '🧀', description: 'Cheese' }, 
          { emoji: '🍖', description: 'Meat on Bone' }, 
          { emoji: '🍗', description: 'Chicken Leg' }, 
          { emoji: '🥩', description: 'Cut of Meat' }, 
          { emoji: '🥓', description: 'Bacon' }, 
          { emoji: '🍔', description: 'Hamburger' }, 
          { emoji: '🍟', description: 'French Fries' }, 
          { emoji: '🍕', description: 'Pizza' }, 
          { emoji: '🌭', description: 'Hot Dog' }, 
          { emoji: '🥪', description: 'Sandwich' }, 
          { emoji: '🌮', description: 'Taco' }, 
          { emoji: '🌯', description: 'Burrito' }, 
          { emoji: '🫔', description: 'Tamale' }, 
          { emoji: '🥙', description: 'Stuffed Flatbread' }, 
          { emoji: '🧆', description: 'Falafel' }, 
          { emoji: '🥚', description: 'Egg' }, 
          { emoji: '🍳', description: 'Cooking Egg' }, 
          { emoji: '🥘', description: 'Pan of Food' }, 
          { emoji: '🍲', description: 'Pot of Food' }, 
          { emoji: '🫕', description: 'Fondue' }, 
          { emoji: '🥣', description: 'Bowl with Spoon' }, 
          { emoji: '🥗', description: 'Green Salad' }, 
          { emoji: '🍿', description: 'Popcorn' }, 
          { emoji: '🧈', description: 'Butter' }, 
          { emoji: '🧂', description: 'Salt' }, 
          { emoji: '🥫', description: 'Canned Food' }, 
          { emoji: '🍱', description: 'Bento Box' }, 
          { emoji: '🍘', description: 'Rice Cracker' }, 
          { emoji: '🍙', description: 'Rice Ball' }, 
          { emoji: '🍚', description: 'Rice' }, 
          { emoji: '🍛', description: 'Curry Rice' }, 
          { emoji: '🍜', description: 'Bowl of Food' }, 
          { emoji: '🍝', description: 'Spaghetti' }, 
          { emoji: '🍠', description: 'Sweet Potato' }, 
          { emoji: '🍢', description: 'Oden' }, 
          { emoji: '🍣', description: 'Sushi' }, 
          { emoji: '🍤', description: 'Shrimp' }, 
          { emoji: '🍥', description: 'Fish Cake' }, 
          { emoji: '🥮', description: 'Moon Cake' }, 
          { emoji: '🍡', description: 'Dango' }, 
          { emoji: '🥟', description: 'Dumpling' }, 
          { emoji: '🥠', description: 'Fortune Cookie' }, 
          { emoji: '🥡', description: 'Takeout Box' }, 
          { emoji: '🦀', description: 'Crab' }, 
          { emoji: '🦞', description: 'Lobster' }, 
          { emoji: '🦐', description: 'Shrimp' }, 
          { emoji: '🦑', description: 'Squid' }, 
          { emoji: '🦪', description: 'Oyster' }, 
          { emoji: '🍦', description: 'Soft Serve Ice Cream'}, 
          { emoji: '🍧', description: 'Shaved Ice' }, 
          { emoji: '🍨', description: 'Ice Cream' }, 
          { emoji: '🍩', description: 'Doughnut' }, 
          { emoji: '🍪', description: 'Cookie' }, 
          { emoji: '🎂', description: 'Birthday Cake' }, 
          { emoji: '🍰', description: 'Shortcake' }, 
          { emoji: '🧁', description: 'Cupcake' }, 
          { emoji: '🥧', description: 'Pie' }, 
          { emoji: '🍫', description: 'Chocolate Bar' }, 
          { emoji: '🍬', description: 'Candy' }
        ],
    
        drink: ['🍼', '🥛', '☕', '🫖', '🍵', '🧃', '🥤', '🍶', '🍺', '🍻', '🥂', '🍷', '🥃', '🍸', '🍹', '🧉', '🍾', '🧊', '🥄', '🍴', '🍽', '🥣', '🥡', '🥢'],
    
        activities: ['⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳', '🪁', '🏹', '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛷', '⛸', '🥌', '🎿', '⛷', '🏂', '🪂', '🏋️‍♀️', '🏋️', '🏋️‍♂️', '🤼‍♀️', '🤼', '🤼‍♂️', '🤸‍♀️', '🤸', '🤸‍♂️', '⛹️‍♀️', '⛹️', '⛹️‍♂️', '🤺', '🤾‍♀️', '🤾', '🤾‍♂️', '🏌️‍♀️', '🏌️', '🏌️‍♂️', '🏇', '🧘‍♀️', '🧘', '🧘‍♂️', '🏄‍♀️', '🏄', '🏄‍♂️', '🏊‍♀️', '🏊', '🏊‍♂️', '🤽‍♀️', '🤽', '🤽‍♂️', '🚣‍♀️', '🚣', '🚣‍♂️', '🧗‍♀️', '🧗', '🧗‍♂️', '🚵‍♀️', '🚵', '🚵'],
    
        travel: [
          '🚗','🚕','🚙','🚌','🚎','🏎','🚓',
          '🚑','🚒','🚐','🚚','🚛','🚜','🦯',
          '🦽','🦼','🛴','🚲','🛵','🏍','🛺',
          '🚨','🚔','🚍','🚘','🚖','🚡','🚠',
          '🚟','🚃','🚋','🚞','🚝','🚄','🚅',
          '🚈','🚂','🚆','🚇','🚊','🚉','🛫',
          '🛬','🛩','💺','🛰','🚀','🛸','🚁',
          '🛶','⛵','🚤','🛥','🛳','🚢','⛽',
          '🚧','🚦','🚥','🚏','🗺','🗿','🗽',
          '🗼','🏰','🏯','🏟','🎡','🎢','🎠',
          '⛲','🏖','🏝','🏜','🌋','🏔','🗻',
          '🏕','⛺','🏠','🏡','🏘','🏚','🏗',
        ],
        objects: [
          '⌚️','📱','📲','💻','🖥','🖨','🖱️',
          '🖲️','🕹️','💿','📞','📷','📸','🎛️',
          '⏱️','⏲️','⏰','🕰️','🕯️','💡','🔦',
          '🏮','🪔','📔','📕','📖','📗','📘',
          '📙','📚','📓','📒','📃','📜','📄',
          '📰','🗞','📑','🔖','🏷','💰','💴',
          '💵','💶','💷','💸','💳','🧾','💹',
          '✉️','📧','📨','📩','📤','📥','📦',
          '📫','📪','📬','📭','📮','📝','💼',
          '📁','📂','🗂','📅','📆','🗒','🗓',
          '📇','📈','📉','📊','📋','📌','📍',
          '📎','🖇','📏','📐','✂️','🗃','🗄',
          '🗑','🔒','🔓','🔏','🔐','🔑','🗝',
          '🔨','🪓','⛏','⚒','🛠','🗡','⚔️',
          '🔫','🏹','🛡','🪚','🔧','🪛','🔩',
          '⚙️','🗜','⚖️','🦯','🔗','⛓','🪝',
          '🧰','🧲','🪜','⚗️','🧪','🧫','🧬',
          '🔬','🔭','📡','💉','🩸','💊','🩹',
          '🩺','🚪','🛏','🛋','🪑','🚽','🚿',
          '🛁','🪒','🧴','🧷','🧹','🧺','🧻',
          '🪣','🧼','🪥','🧽','🧯','🛒','🚬',
        ],
        hearts: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝'],
        symbols: [
          '🔟','🔢','🔣','🔠','🔡','🔤','🅰️',
          '🆎','🅱️','🆑','🆒','🆓','ℹ️','🆔',
          'Ⓜ️','🆕','🆖','🅾️','🆗','🅿️','🆘',
          '🆙','🆚','🈁','🈂️','🈷️','🈶','🈯',
          '🉐','🈹','🈚','🈲','🉑','🈸','🈴',
          '🈳','㊗️','㊙️','🈺','🈵','🔴','🟠',
          '🟡','🟢','🔵','🟣','🟤','⚫','⚪',
          '🟥','🟧','🟨','🟩','🟦','🟪','🟫',
          '⬛','⬜','🔶','🔷','🔸','🔹','🔺','🔻',
          '💠','🔘','🔳','🔲'
        ],
        flags: [
          '🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🏴‍☠️',
          '🇦🇨','🇦🇩','🇦🇪','🇦🇫','🇦🇬','🇦🇮','🇦🇱',
          '🇦🇲','🇦🇴','🇦🇶','🇦🇷','🇦🇸','🇦🇹','🇦🇺',
          '🇦🇼','🇦🇽','🇦🇿','🇧🇦','🇧🇧','🇧🇩','🇧🇪',
          '🇧🇫','🇧🇬','🇧🇭','🇧🇮','🇧🇯','🇧🇱','🇧🇲',
          '🇧🇳','🇧🇴','🇧🇶','🇧🇷','🇧🇸','🇧🇹','🇧🇻',
          '🇧🇼','🇧🇾','🇧🇿','🇨🇦','🇨🇨','🇨🇩','🇨🇫',
          '🇨🇬','🇨🇭','🇨🇮','🇨🇰','🇨🇱','🇨🇲','🇨🇳',
          '🇨🇴','🇨🇵','🇨🇷','🇨🇺','🇨🇻','🇨🇼','🇨🇽',
          '🇨🇾','🇨🇿','🇩🇪','🇩🇬','🇩🇯','🇩🇰','🇩🇲',
          '🇩🇴','🇩🇿','🇪🇦','🇪🇨','🇪🇪','🇪🇬','🇪🇭',
          '🇪🇷','🇪🇸','🇪🇹','🇪🇺','🇫🇮','🇫🇯','🇫🇰',
          '🇫🇲','🇫🇴','🇫🇷','🇬🇦','🇬🇧','🇬🇩','🇬🇪',
          '🇬🇫','🇬🇬','🇬🇭','🇬🇮','🇬🇱','🇬🇲','🇬🇳',
          '🇬🇵','🇬🇶','🇬🇷','🇬🇸','🇬🇹','🇬🇺','🇬🇼',
          '🇬🇾','🇭🇰','🇭🇲','🇭🇳','🇭🇷','🇭🇹','🇭🇺',
          '🇮🇨','🇮🇩','🇮🇪','🇮🇱','🇮🇲','🇮🇳','🇮🇴',
          '🇮🇶','🇮🇷','🇮🇸','🇮🇹','🇯🇪','🇯🇲','🇯🇴',
          '🇯🇵','🇰🇪','🇰🇬','🇰🇭','🇰🇮','🇰🇲','🇰🇳',
          '🇰🇵','🇰🇷','🇰🇼','🇰🇾','🇰🇿','🇱🇦','🇱🇧',
          '🇱🇨','🇱🇮','🇱🇰','🇱🇷','🇱🇸','🇱🇹','🇱🇺',
          '🇱🇻','🇱🇾','🇲🇦','🇲🇨','🇲🇩','🇲🇪','🇲🇫',
          '🇲🇬','🇲🇭','🇲🇰','🇲🇱','🇲🇲','🇲🇳','🇲🇴',
          '🇲🇵','🇲🇶','🇲🇷','🇲🇸','🇲🇹','🇲🇺','🇲🇻',
          '🇲🇼','🇲🇽','🇲🇾','🇲🇿','🇳🇦','🇳🇨','🇳🇪',
          '🇳🇫','🇳🇬','🇳🇮','🇳🇱','🇳🇴','🇳🇵','🇳🇷',
          '🇳🇺','🇳🇿','🇴🇲','🇵🇦','🇵🇪','🇵🇫','🇵🇬',
          '🇵🇭','🇵🇰','🇵🇱','🇵🇲','🇵🇳','🇵🇷','🇵🇸',
          '🇵🇹','🇵🇼','🇵🇾','🇶🇦','🇷🇪','🇷🇴','🇷🇸',
          '🇷🇺','🇷🇼','🇸🇦','🇸🇧','🇸🇨','🇸🇩','🇸🇪',
          '🇸🇬','🇸🇭','🇸🇮','🇸🇯','🇸🇰','🇸🇱','🇸🇲',
          '🇸🇳','🇸🇴','🇸🇷','🇸🇸','🇸🇹','🇸🇻','🇸🇽',
          '🇸🇾','🇸🇿','🇹🇦','🇹🇨','🇹🇩','🇹🇫','🇹🇬',
          '🇹🇭','🇹🇯','🇹🇰','🇹🇱','🇹🇲','🇹🇳','🇹🇴',
          '🇹🇷','🇹🇹','🇹🇻','🇹🇼','🇹🇿','🇺🇦','🇺🇬',
          '🇺🇲','🇺🇳','🇺🇸','🇺🇾','🇺🇿','🇻🇦','🇻🇨',
          '🇻🇪','🇻🇬','🇻🇮','🇻🇳','🇻🇺','🇼🇫','🇼🇸',
          '🇽🇰','🇾🇪','🇾🇹','🇿🇦','🇿🇲','🇿🇼','🏴‍☠️',
          '🏴󠁧󠁢󠁥󠁮󠁧󠁿','🏴󠁧󠁢󠁳󠁣󠁴󠁿','🏴󠁧󠁢󠁷󠁬󠁳󠁿',
        ]
      };

      return emojiCategories;
}